In [0]:
def test():
    print('test() for function')
    return
test()

test() for function


In [0]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return

obj=Demo()
obj.test()

test() for the class and method


In [0]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact =1
        while(n!=0):
             fact=fact * n
             n=n -1
        return fact
p1=Demo1()
print(p1.fact(5))
      

120


In [0]:
class Demo2:
    def accept(self,p1,p2):
      self.p1=p1
      self.p2=p2
      return
    def display(self):
        print("a= ",a)
        print("b= ",b)
        
c1=Demo2()
c1.accept(10,20)
c1.display()

NameError: ignored

In [0]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [28]:
import numpy as np
lst=[1,2,3,4,5]
array=np.array(lst);
print(array)

[1 2 3 4 5]


In [9]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [10]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))


[1 2 3 4 5 6]


In [12]:
a1=np.random.normal(5,0.5,10)
print(a1)

[5.7257482  4.95211412 4.43354978 4.93326845 4.40699257 5.011138
 5.16646467 4.45922538 4.62928723 5.1239325 ]


In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [17]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [25]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [27]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [29]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [32]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [34]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [35]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[1])

first row : [4 5 6]


In [36]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])

second row : [4 5 6]


In [37]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])

slicing column : [2 5]


In [38]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column :",a1[:,2])

slicing last column : [3 6]


In [39]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column",a1[1,:1])

row and column [4]


In [41]:
import pandas as pd
dict={"name":["abc","def","ghi","jkl","mno"],"EmailID":["123","456","789","012","345"],"mbn":["222","345","778","000","444"],"add":["yyy","u","i","o","p"]}
b=pd.dataFrame(dict)
print(b)

AttributeError: ignored